### ISSUE TITLE
Sounds broken?

### ISSUE THREAD

**Issue by utkusucu** [PacharaGOD/Apex-Legend-No-recoil-AHK-script-2021#2]
Did you mess up or change the audio codes? because the speaker is not speaking lol.

**Comment by PacharaGOD** [comment]
idk bro I dont think so

**Comment by utkusucu** [comment]
> Idk bro I don't think so

Normally there should be a sound like if you press f1 speaker should say r301 or mr301

**Comment by utkusucu** [comment]
Ok, I fixed it.
To turn on the speaker's voice, you should go Base Stats section in the code and set the volume 80.

**Comment by PacharaGOD** [comment]
ok bro thank
